	<section id="sec-preface" class="prechapter">
		<h2 id="preface">Preface</h2>
		<p>The origins of this book can be traced back to a Dagstuhl Seminar, held in 2018, on the topic of Knowledge Graphs. At the time of the seminar, the topic was quickly becoming mainstream in academia and industry, but there were conflicting messages as to what a “knowledge graph” was. Much of the discussion of the seminar centred on this question, and there were divergent opinions as to how knowledge graphs could (or should) be defined; how they relate to previous concepts such as graph databases, knowledge bases, ontologies, RDF graphs, property graphs, semantic networks, etc.; and how the emerging area of Knowledge Graphs should be positioned with respect to the established areas of Artificial Intelligence, Big Data, Databases, Graph Theory, Logic, Machine Learning, Knowledge Representation, Natural Language Processing, Networks (in their various forms), and the Semantic Web. As the discussion continued, a consensus began to emerge: Knowledge Graphs, as a topic, involves a novel confluence of techniques stemming from previously disparate scientific communities, with the unifying goal of developing novel graph-based techniques for better integrating and extracting value from diverse knowledge sources at large scale.</p>
		<p>As a follow-up to the seminar, the attendees agreed that in order to foster this unifying view of Knowledge Graphs, there was a clear need for a manuscript that would serve as a general introduction to the area written from this perspective. This manuscript would:</p>
		<ul>
			<li>motivate knowledge graphs and the value of applying a graph abstraction to data;</li>
			<li>survey the historical context of knowledge graphs and the key initiatives leading to their popularisation;</li>
			<li>draw together the disparate views of knowledge graphs into a unifying definition;</li>
			<li>provide an introduction to the key techniques that knowledge graphs enable, relating to querying, validation, reasoning, learning, refinement, enrichment, quality assessment, and more besides;</li>
			<li>describe how knowledge graphs are used in practice, in terms of what companies and industries have been adopting them, for which applications; what open knowledge graphs have been published, and what they describe; etc.</li>
			<li>delineate future research directions for knowledge graphs.</li>
		</ul>
		<p>The manuscript would then serve as an introductory text for students, practitioners and researchers new to the area, while also serving as a way to build a broader, unifying consensus in terms of what is a knowledge graph, and to lay the foundations for their future development.</p>
		<p>Needless to say, the goal of preparing this manuscript was an ambitious one, and required drawing together and distilling down a vast amount of literature on a diverse range of topics into a set of key concepts described in an accessible way. For this reason, the manuscript has been prepared by many authors, who have lent their knowledge and expertise to the preparation of specific sections. Many of these authors were attendees of the original seminar who volunteered for this initiative, and other authors were later invited to further bolster the discussion on specific topics within their area of expertise. Preparation of the core content spanned two years, and several iterations, towards achieving a cohesive, broad, and accessible introduction to the area of Knowledge Graphs.</p>
		<p>A key aim of this book is to be accessible to a broader audience. While background knowledge of related topics such as Databases, Logic, Machine Learning, Semantic Web, etc., will help to understand some of the particular topics mentioned, such a background is not necessary to follow the general concepts described within. The book aims to motivate and illustrate the various concepts it introduces from a practical perspective, and in order to be as accessible as possible, relies heavily on an example-driven presentation using a graphical notation. For the reader wishing to dig more into the technical minutiae, we complement this discussion with formal definitions throughout; however, the reader more interested in understanding the general concepts and their rationale will find the discussion to be self-contained if they choose to skip the definitions presented in visually distinctive boxes.</p>
		<p>The book serves as an entry point for those new to the topic, and may thus serve as a useful textbook for university courses, for researchers who are venturing into the topic for the first time, and for practitioners who wish to understand more about how knowledge graphs might be of use within their company or organisation, or indeed, how to maximise the value of the knowledge graphs that they are developing. Readers who are already active within specific sub-areas of Knowledge Graphs may further appreciate the technical definitions included, the references to other literature provided, and the broader perspective that this book offers in terms of the other related sub-areas and how they complement each other.</p>
		<p>By drawing together diverse techniques from disparate areas, Knowledge Graphs has become an exciting topic in terms of both research and applications. We expect to see growing interest on this topic as the years advance, and indeed hope that this book will help to more firmly establish the foundations of this topic, and to foster future developments upon these foundations – perhaps by its readers.</p>
		<p style="text-align: right; font-style: italic;">Aidan&nbsp;Hogan, Eva&nbsp;Blomqvist, Michael&nbsp;Cochez, Claudia&nbsp;d’Amato, Gerard&nbsp;de&nbsp;Melo, Claudio&nbsp;Gutierrez, Sabrina&nbsp;Kirrane, José&nbsp;Emilio&nbsp;Labra&nbsp;Gayo, Roberto&nbsp;Navigli, Sebastian&nbsp;Neumaier, Axel-Cyrille&nbsp;Ngonga&nbsp;Ngomo, Axel&nbsp;Polleres, Sabbir&nbsp;M.&nbsp;Rashid, Anisa&nbsp;Rula, Lukas&nbsp;Schmelzeisen, Juan&nbsp;Sequeda, Steffen&nbsp;Staab, Antoine&nbsp;Zimmermann<br/>
		June 2021</p>
	</section>
