	<section id="chap-conclude" class="chapter">
		<h2>Summary and Conclusion</h2>
		<p>We have provided a comprehensive introduction to knowledge graphs, which have been receiving more and more attention in recent years. Under the definition of a knowledge graph as <em>a graph of data intended to accumulate and convey knowledge of the real world, whose nodes represent entities of interest and whose edges represent relations between these entities</em>, we have discussed models by which data can be structured as graphs; representations of schema, identity and context; techniques for leveraging deductive and inductive knowledge; methods for the creation, enrichment, quality assessment and refinement of knowledge graphs; principles and standards for publishing knowledge graphs; and finally, we have discussed the adoption of both open and enterprise knowledge graphs in the real world.</p>
		<p>In this final chapter, we provide some concluding remarks, and further offer some insights on potential future directions for research on knowledge graphs.</p>
		<p><em class="paragraph">Concluding remarks</em>. Knowledge graphs have garnered significant attention not only from diverse organisations and industries, but also diverse research communities. This attention is due, in no small part, to the ubiquitous nature of the problem that knowledge graphs address: integrating and extracting value from diverse sources of data at large scale, be it in the context of a particular organisation, community, or more general collections of human knowledge. The key insight of knowledge graphs is that graphs provide a simple, flexible, intuitive and yet powerful abstraction for representing and integrating diverse data at large scale. This insight is far from new (see Appendix&nbsp;<? echo ref("chap:defs"); ?>), but rather has finally come of age with the advent of knowledge graphs. Graphs have long been used to represent data and knowledge in areas such as Graph Algorithms and Theory, Graph Databases, Information Extraction, Knowledge Representation, Machine Learning, the Semantic Web, and more besides. The advances in these areas can now be unified and applied for knowledge graphs.</p>
		<p>Thus, the decision to model data as a graph opens up a “tool-box” of languages, techniques and systems – stemming from diverse areas – that can be deployed in order to integrate and extract value from data at large scale, as follows:</p>
		<ul>
			<li>A variety of <em>graph query languages</em> are now available that (unlike other NoSQL alternatives) are fully-featured, supporting not only the relational algebra, but also novel features such as navigational queries that can match paths of arbitrary length. A broad selection of graph databases and user interfaces supporting these query languages are now also available.</li>
			<li>Though graphs do not depend on a detailed (relational-like) schema to represent data, various notions of <em>graph schemata</em> have been proposed in order to validate, summarise and define the semantics of graphs.</li>
			<li><em>Contextual frameworks for graphs</em> can be used to represent and reason about the scope of truth of knowledge in the graph – relating to the time, space, provenance, confidence level, etc., for which something is held true – including various alternatives for reification, annotated graph frameworks, etc.</li>
			<li>Deductive forms of reasoning can be enabled over graphs using <em>ontologies</em> and/or <em>rules</em>, which can not only encode a machine-readable consensus about the meaning of the graph, but also provide automated access to implicit knowledge entailed by a graph through materialisation or query rewriting.</li>
			<li><em>Graph algorithms</em>, such as centrality measures, community detection, clustering, etc., can be applied on the data to gain insights about influential entities or edges, close-knit sub-graphs of entities, and more besides, with <em>graph parallel frameworks</em> capable of applying such algorithms at large scale.</li>
			<li>Recent and continual advances in <em>knowledge graph embeddings</em> and <em>graph neural networks</em> have now opened up new possibilities for applying machine learning natively over graphs in the context of diverse tasks, including classification, question answering, recommendations, and more besides.</li>
			<li><em>Rule and axiom mining</em> techniques allow for extracting formal, declarative hypotheses from a knowledge graph that encode high-level patterns and can be applied to derive new knowledge in a deductive, explainable manner.</li>
			<li><em>Graph-based information extraction</em> can be applied to extract and/or enrich a knowledge graph from legacy sources of text and semi-structured data, while <em>graph-based mapping languages</em> facilitate integrating diverse sources of legacy structured data into the knowledge graph.</li>
			<li>Tools, techniques and methodologies for <em>ontology engineering</em> and <em>ontology learning</em> can further guide the – potentially collaborative – creation of an ontology for the knowledge graph, encoding a consensus about its semantics, and enabling access to implicit knowledge through deductive reasoning.</li>
			<li><em>Quality dimensions and metrics for knowledge graphs</em> allow for systematically assessing the readiness of the knowledge graph for its envisaged applications, in both a qualitative and quantitative manner, where a variety of tools and frameworks are available to help perform such assessments.</li>
			<li>Knowledge graphs that have been integrated from diverse sources are likely to be incomplete, or to encode incorrect data, where techniques and tools for <em>knowledge graph refinement</em> facilitate the automated completion and correction of knowledge graphs, thus improving its overall quality and usefulness.</li>
			<li>For the purposes of publishing open knowledge graphs, <em>principles &amp; best practices</em> and <em>access protocols</em>, as well as techniques for <em>linking</em>, <em>licensing</em>, <em>access &amp; usage control</em>, <em>encryption</em> and <em>anonymisation</em>, can be leveraged to maximise their potential impact on society in an ethical way.</li>
		</ul>
		<p>As we have discussed in Chapter&nbsp;<? echo ref("chap:kgs"); ?>, the various components of this “knowledge graph tool-box” can already be found deployed in practice, having been applied – to varying degrees – in the context of numerous open and enterprise knowledge graphs. As adoption of knowledge graphs continues, work will also continue on improving and combining these tools, as well as on developing novel tools that help to better integrate and extract value from diverse sources of data at large scale.</p>
		<p><em class="paragraph">Future directions</em>. Research on knowledge graphs involves a confluence of techniques from different research areas with the common objective of maximising the knowledge – and thus value – that can be distilled from diverse sources at large scale using a graph-based data abstraction&nbsp;<? echo $references->cite("Hogan20"); ?>.</p>
		<p>In the intersection of data graphs and deductive knowledge, we emphasise emerging topics such as <em>formal semantics for property graphs</em>, with languages that can take into account the meaning of labels and property–value pairs on nodes and edges&nbsp;<? echo $references->cite("Krotzsch0OT18"); ?>; and <em>reasoning and querying over contextual data</em>, in order to derive conclusions and results valid in a particular setting&nbsp;<? echo $references->cite("SerafiniH12,zimm-etal-2012-JWS,SchuetzBNSS20"); ?>. In the intersection of data graphs and inductive knowledge, we highlight topics such as <em>similarity-based query relaxation</em>, allowing to find approximate answers to exact queries based on numerical representations (e.g., embeddings)&nbsp;<? echo $references->cite("WangWLCZQ18"); ?>; <em>shape induction</em>, in order to learn and formalise inherent patterns in the knowledge graph as constraints&nbsp;<? echo $references->cite("Mihindukulasooriya18"); ?>; and <em>contextual knowledge graph embeddings</em> that provide numeric representations of nodes and edges that vary with time, place, etc.&nbsp;<? echo $references->cite("KazemiGJKSFP19"); ?>. In the intersection of deductive and inductive knowledge, we mention the topics of <em>entailment-aware knowledge graph embeddings</em>&nbsp;<? echo $references->cite("GuoWWWG16,DemeesterRR16"); ?>, that incorporate rules and/or ontologies when computing plausibility; <em>expressive graph neural networks</em> proven capable of complex classification analogous to expressive ontology languages&nbsp;<? echo $references->cite("BarceloKMPRS20"); ?>; as well as further advances on <em>rule and axiom mining</em>, allowing to extract symbolic, deductive representations from the knowledge graphs&nbsp;<? echo $references->cite("GalarragaTHS15,BuhmannLW16"); ?>. Further challenges arise when considering the creation, enrichment, refinement and publication of knowledge graphs, which call for further works on topics such as <em>automated quality assessment (and repair)</em>, <em>distantly-supervised extraction frameworks</em>, <em>efficient access protocols</em>, and <em>anonymisation</em>, to name but a few.</p>
		<p>Aside from specific topics, more general challenges for knowledge graphs include <em>scalability</em>, particularly for deductive and inductive reasoning; <em>quality</em>, not only in terms of data, but also the models induced from knowledge graphs; <em>diversity</em>, such as managing contextual or multi-modal data; <em>dynamicity</em>, considering temporal or streaming data; and finally <em>usability</em>, which is key to increasing adoption. Though techniques are continuously being proposed to address these challenges, they are unlikely to ever be completely “solved”; rather they serve as dimensions along which knowledge graphs, and their techniques, tools, etc., will continue to mature.</p>
		<p>Given the availability of open knowledge graphs whose quality continues to improve, as well as the growing adoption of enterprise knowledge graphs in various industries, future research on knowledge graphs has the potential to foster key advancements in broad aspects of society. Here we have highlighted just some examples of future research directions of importance to this pursuit.</p>
	</section>
